root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/api/app/main.go"
  bin = "./tmp/main"
  full_bin = "./cmd/.env"
  log = "tmp/build-errors.log"
  exclude_dir = ["assets", "vendor", "testdata", "tmp"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
  show_build_errors = true

[watch]
  dir = ["./cmd", "./pkg"]
