// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package bridge

import (
	"time"
)

type User struct {
	ID        int32
	Name      string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
